### ISSUE TITLE
Feature request: support REPLish workflow

### ISSUE THREAD

**Issue by ethercrow** [schell/steeloverseer#35]
I wonder if a typical ghci workflow can be automated with sos.

Usually you run a ghci process and:
1. When `*.hs` changes, you send `:r<CR>` or possibly `:r<CR>:main<CR>` to ghci
2. When `*.cabal` or `*.yaml` changes, you restart ghci
3. Also you're able to type stuff into currently running ghci

Right now 2. is working perfectly, 3. works kind of weird (I'm not even sure how to describe it) and 1. is not covered at all.

Meanwhile, ghcid supports 1 and 2, but not 3 (by current design) and naturally only supports ghci. Ideally I'd like to be able to use sos to automate a REPL workflow for any language, e.g. restart the process on `project.clj` changes and send `(run-all-tests)<CR>` on other changes.

**Comment by schell** [comment]
This is a good idea.

**Comment by jappeace** [comment]
Instead of focusing on making a repl work, how about making *any* shell work (since a repl is just a shell).
I want something similar but execute stuff in a nix shell instead.

Something like:

```yaml
commands: 
   - shell: ghci
     command: :r 
     invalidate: *.yaml *.cabal
   - shell: nix-shell
     command: cabal new-build -j --ghc-options --no-code
     invalidate: *.nix
```
